{
 "title": "Sparvio map",
 "description": "Plot the locations of measurements",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "temp_src",
    "label": "Temperature sensor",
    "query": "show tag values with key=\"sensor\""
   }
  ]
 },
 "panels": [
  {
   "title": "T over area",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "lon",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "lat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$temp_src$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2 over area",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "lon",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "lat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "alt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Carbon dioxide",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Warnings", "type": "alertlist", "gridPos": { "h": 4, "w": 10, "x": 14, "y": 15 } }
 ]
}