{
 "title": "Sparvio",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "logDo",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery voltage (V)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "V" }
   ],
   "targets": [
    {
     "limit": "0",
     "measurement": "bat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Radio reception",
   "type": "graph",
   "description": "Shows each received data packet with reception quality, where 100% is perfect and 0% is non-existent. All data is valid regardless of reception quality but low quality indicates a risk of dropping intermediate packets.",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Reception" }
   ],
   "targets": [
    {
     "measurement": "reception",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Warnings", "type": "alertlist", "gridPos": { "h": 4, "w": 6, "x": 16, "y": 1 } },
  { "title": "Temperature, humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "baroTemp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "pcbTemp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "limit": "0",
     "measurement": "rh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Altitude and pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Altitude and pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "Air pressure (Pa)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "limit": "0",
     "measurement": "pr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Altitude from pressure",
     "measurement": "alt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "SKH1" }
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "alt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "SKH1" }
     ]
    }
   ]
  },
  { "title": "Carbon dioxide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Carbon dioxide",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "limit": "0",
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "co2Flt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "co2Unflt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Carbon dioxide",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ozone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ozone (ppm)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "sensor" ], "type": "tag" }
       ],
       "measurement": "o3ppm",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "10m" ], "type": "time" },
        { "params": [ "sensor" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "o3ppm",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Particulate matter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Particulate Matter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "ug/m3" }
   ],
   "targets": [
    {
     "alias": "PM 1",
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "pm1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PM 2.5",
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "pm2_5",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PM 10",
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "pm10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historic values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Numeric values",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "sensor" ], "type": "tag" }
       ],
       "measurement": "temp",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "sensor" ], "type": "tag" }
       ],
       "measurement": "rh",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CO2 per altitude",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Co2 per altitude",
     "type": "natel-plotly-panel",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "measurement": "co2",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "sensor", "operator": "=", "value": "K30" }
       ]
      },
      {
       "measurement": "alt",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "sensor", "operator": "=", "value": "SKH1" }
       ]
      }
     ]
    }
   ]
  }
 ]
}