{
 "title": "Winds",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Wind speed / direction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wind speed (relative)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "wspd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "wdir",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wind U, V, W",
     "type": "graph",
     "gridPos": { "h": 14, "w": 21, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "sensor" ], "type": "tag" }
       ],
       "measurement": "u",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "sensor" ], "type": "tag" }
       ],
       "measurement": "v",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "sensor" ], "type": "tag" }
       ],
       "measurement": "w",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}